version: 2

defaults: &defaults
  working_directory: /tmp/app

jobs:
  pre-publish:
    <<: *defaults
    docker:
      - image: alpine/git
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Set container destination
          command: |
            touch .destination
            if git describe --exact-match HEAD > /dev/null 2>&1; then
              echo "--destination ghcr.io/markormesher/${CIRCLE_PROJECT_REPONAME}:$(git describe --tags)" | tee .destination
            else
              echo "--no-push" | tee .destination
            fi
      - persist_to_workspace:
          root: .
          paths:
            - .

  publish:
    <<: *defaults
    docker:
      - image: gcr.io/kaniko-project/executor:v1.17.0-debug
        entrypoint: ""
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Build container image
          command: |
            AUTH=$(echo -n "markormesher:${GHCR_PUBLISH_TOKEN}" | base64)
            echo '{"auths":{"ghcr.io":{"auth":"'${AUTH}'"}}}' > /kaniko/.docker/config.json
            /kaniko/executor \
              --verbosity debug \
              --context dir:///tmp/app \
              --ignore-path /tmp/app \
              $(cat .destination)

workflows:
  version: 2
  main:
    jobs:
      - pre-publish
      - publish:
          requires:
            - pre-publish
